export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GETUSERS_SUCCESS = "GETUSERS_SUCCESS";
export const GETUSERS_FAIL = "GETUSERS_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GETJOBS_SUCCESS = "GETJOBS_SUCCESS";
export const GETJOBS_FAIL = "GETJOBS_FAIL";
export const ADDJOB_SUCCESS = "ADDJOB_SUCCESS";
export const ADDJOB_FAIL = "ADDJOB_FAIL";
export const UPDATEJOB_SUCCESS = "UPDATEJOB_SUCCESS";
export const UPDATEJOB_FAIL = "UPDATEJOB_FAIL";
export const DELETEJOB_SUCCESS = "DELETEJOB_SUCCESS";
export const DELETEJOB_FAIL = "DELETEJOB_FAIL";
export const JOB_SELECTED_ROW = "JOB_SELECTED_ROW";
export const ASSOCIATECANDIDATE_SUCCESS = "ASSOCIATECANDIDATE_SUCCESS";
export const ASSOCIATECANDIDATE_FAIL = "ASSOCIATECANDIDATE_FAIL";
export const UPDATECANDIDATESTATUS_SUCCESS = "UPDATECANDIDATESTATUS_SUCCESS";
export const UPDATECANDIDATESTATUS_FAIL = "UPDATECANDIDATESTATUS_FAIL";
export const DESELECT_JOBS_GRID = "DESELECT_JOBS_GRID";
export const GETPREFFEREDCANDIDATE_SUCCESS = "GETPREFFEREDCANDIDATE_SUCCESS";
export const GETPREFFEREDCANDIDATE_FAIL = "GETPREFFEREDCANDIDATE_FAIL";


export const GETCLIENTS_SUCCESS = "GETCLIENTS_SUCCESS";
export const GETCLIENTS_FAIL = "GETCLIENTS_FAIL";
export const ADDCLIENTS_SUCCESS = "ADDCLIENTS_SUCCESS";
export const ADDCLIENTS_FAIL = "ADDCLIENTS_FAIL";
export const UPDATECLIENTS_SUCCESS = "UPDATECLIENTS_SUCCESS";
export const UPDATECLIENTS_FAIL = "UPDATECLIENTS_FAIL";
export const DELETECLIENT_SUCCESS = "DELETECLIENT_SUCCESS";
export const DELETECLIENT_FAIL = "DELETECLIENT_FAIL";
export const CLIENT_SELECTED_ROW = "CLIENT_SELECTED_ROW";

export const GETVENDORS_SUCCESS = "GETVENDORS_SUCCESS";
export const GETVENDORS_FAIL = "GETVENDORS_FAIL";
export const ADDVENDORS_SUCCESS = "ADDVENDORS_SUCCESS";
export const ADDVENDORS_FAIL = "ADVENDORSS_FAIL";
export const UPDATEVENDORS_SUCCESS = "UPDATEVENDORS_SUCCESS";
export const UPDATEVENDORS_FAIL = "UPDATEVENDORS_FAIL";
export const DELETEVENDOR_SUCCESS = "DELETEVENDOR_SUCCESS";
export const DELETEVENDOR_FAIL = "DELETEVENDOR_FAIL";
export const VENDOR_SELECTED_ROW = "VENDOR_SELECTED_ROW";
export const GETVENDORSBYID_SUCCESS="GETVENDORSBYID_SUCCESS";
export const GETVENDORSBYID_FAIL="GETVENDORSBYID_FAIL"

export const SEARCHPRESSENTER = "SEARCHPRESSENTER";
export const GETCANDIDATES_SUCCESS = "GETCANDIDATES_SUCCESS";
export const GETCANDIDATES_FAIL = "GETCANDIDATES_FAIL";
export const GETCANDIDATESBYID_SUCCESS = "GETCANDIDATESBYID_SUCCESS";
export const GETCANDIDATESBYID_FAIL = "GETCANDIDATESBYID_FAIL";
export const ADDCANDIDATE_SUCCESS = "ADDCANDIDATE_SUCCESS";
export const ADDCANDIDATE_FAIL = "ADDCANDIDATE_FAIL";
export const UPDATECANDIDATE_SUCCESS = "UPDATECANDIDATE_SUCCESS";
export const UPDATECANDIDATE_FAIL = "UPDATECANDIDATE_FAIL";
export const CANDIDATE_SELECTED_ROW = "CANDIDATE_SELECTED_ROW";
export const DELETECANDIDATE_SUCCESS = "DELETECANDIDATE_SUCCESS";
export const DELETECANDIDATE_FAIL = "DELETECANDIDATE_FAIL";
export const PARSECANDIDATE_PENDING = "PARSECANDIDATE_PENDING";
export const PARSECANDIDATE_SUCCESS = "PARSECANDIDATE_SUCCESS";
export const PARSECANDIDATE_FAIL = "PARSECANDIDATE_FAIL";

export const UPLOADFILE_SUCCESS = "UPLOADFILE_SUCCESS";
export const UPLOADFILE_FAIL = "UPLOADFILE_FAIL";
export const DOWNLOADFILE_SUCCESS = "DOWNLOADFILE_SUCCESS";
export const DOWNLOADFILE_FAIL = "DOWNLOADFILE_FAIL";

export const GETJOBNOTES_SUCCESS = "GETJOBNOTES_SUCCESS";
export const GETJOBNOTES_FAIL = "GETJOBNOTES_FAIL";
export const ADDJOBNOTES_SUCCESS = "ADDJOBNOTES_SUCCESS";
export const ADDJOBNOTES_FAIL = "ADDJOBNOTES_FAIL";
export const UPDATEJOBNOTES_SUCCESS = "UPDATEJOBNOTES_SUCCESS";
export const UPDATEJOBNOTES_FAIL = "UPDATEJOBNOTES_FAIL";
export const DELETEJOBNOTES_SUCCESS = "DELETEJOB_SUCCESS";
export const DELETEJOBNOTES_FAIL = "DELETEJOBNOTES_FAIL";

export const GETCANDIDATENOTES_SUCCESS = "GETCANDIDATENOTES_SUCCESS";
export const GETCANDIDATENOTES_FAIL = "GETCANDIDATENOTES_FAIL";
export const ADDCANDIDATENOTES_SUCCESS = "ADDCANDIDATENOTES_SUCCESS";
export const ADDCANDIDATENOTES_FAIL = "ADDCANDIDATENOTES_FAIL";
export const UPDATECANDIDATENOTES_SUCCESS = "UPDATECANDIDATENOTES_SUCCESS";
export const UPDATECANDIDATENOTES_FAIL = "UPDATECANDIDATENOTES_FAIL";
export const DELETECANDIDATENOTES_SUCCESS = "DELETECANDIDATENOTES_SUCCESS";
export const DELETECANDIDATENOTES_FAIL = "DELETECANDIDATENOTES_FAIL";
//search
export const SEARCHCANDIDATE_SUCCESS = "SEARCHCANDIDATE_SUCCESS";
export const SEARCHCANDIDATE_FAIL = "SEARCHCANDIDATE_FAIL";

export const GETACTIVITY_SUCCESS = "GETACTIVITY_SUCCESS";
export const GETACTIVITY_FAIL = "GETACTIVITY_FAIL";
export const GETNOTIFICATION_SUCCESS = "GETNOTIFICATION_SUCCESS";
export const GETNOTIFICATION_FAIL = "GETNOTIFICATION_FAIL";

export const GETREPORTS_SUCCESS = "GETREPORTS_SUCCESS";
export const GETREPORTS_FAIL = "GETREPORTS_FAIL";

export const GETUSERPROFILE_SUCCESS = "GETUSERPROFILE_SUCCESS";
export const GETUSERPROFILE_FAIL = "GETUSERPROFILE_FAIL";

export const UPDATEUSERPROFILE_SUCCESS = "UPDATEUSERPROFILE_SUCCESS";
export const UPDATEUSERPROFILE_FAIL = "UPDATEUSERPROFILE_FAIL";

export const DELETEUSER_SUCCESS = "DELETEUSER_SUCCESS";
export const DELETEUSER_FAIL = "DELETEUSER_FAIL";